name: ai_interview_coach
description: AI-powered interview practice application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  
  
  cloud_firestore: ^5.6.12
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & Networking
  http: ^1.2.2
  
  # Speech Recognition
  speech_to_text: ^6.6.0
  permission_handler: ^11.1.0
  
  # UI & Animations
  material_color_utilities: ^0.11.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # PDF Export
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.1

  # login reques
  flutter_dotenv: ^6.0.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/.env
    - assets/config.json


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf

  