// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRR3XQdncI3612bb4WG_i8tKzaG-MMlaA',
    appId: '1:27984765300:web:fe37f22609eaf9fe3e0c21',
    messagingSenderId: '27984765300',
    projectId: 'ai-interview-project-6e392',
    authDomain: 'ai-interview-project-6e392.firebaseapp.com',
    storageBucket: 'ai-interview-project-6e392.firebasestorage.app',
    measurementId: 'G-TCBYYM5N56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrHzJ2FMNvvsTaY410JTYizGvq-OMtQ0M',
    appId: '1:27984765300:android:b3f83af7bd57a8773e0c21',
    messagingSenderId: '27984765300',
    projectId: 'ai-interview-project-6e392',
    storageBucket: 'ai-interview-project-6e392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4q8tpaWuERJrwMziB1bTi1bV6oRA8IC0',
    appId: '1:27984765300:ios:b11665045d8cd8db3e0c21',
    messagingSenderId: '27984765300',
    projectId: 'ai-interview-project-6e392',
    storageBucket: 'ai-interview-project-6e392.firebasestorage.app',
    iosClientId: '27984765300-g8r6kfm9iq2oe8t3i81i0u4jlcsvv17m.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiInterviewCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4q8tpaWuERJrwMziB1bTi1bV6oRA8IC0',
    appId: '1:27984765300:ios:b11665045d8cd8db3e0c21',
    messagingSenderId: '27984765300',
    projectId: 'ai-interview-project-6e392',
    storageBucket: 'ai-interview-project-6e392.firebasestorage.app',
    iosClientId: '27984765300-g8r6kfm9iq2oe8t3i81i0u4jlcsvv17m.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiInterviewCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRR3XQdncI3612bb4WG_i8tKzaG-MMlaA',
    appId: '1:27984765300:web:2e36f54cacbdc6703e0c21',
    messagingSenderId: '27984765300',
    projectId: 'ai-interview-project-6e392',
    authDomain: 'ai-interview-project-6e392.firebaseapp.com',
    storageBucket: 'ai-interview-project-6e392.firebasestorage.app',
    measurementId: 'G-9KEPLGSDBS',
  );

}